### ISSUE TITLE
Duplicated merge request

### ISSUE THREAD

**Issue by javiplx** [javiplx/jenkins-gitlab-hook-plugin#67]
If a merge request creation is replayed, it is unclear whether it is properly handled or an exception happens

    Mar 14, 2015 12:22:45 AM sun.reflect.NativeMethodAccessorImpl invoke0
    INFO: matching projects:
       - gitlab-hook-plugin
       - gitlab-hook-plugin-mr-feature_clear_notifiers_on_mr
    Mar 14, 2015 12:22:45 AM sun.reflect.GeneratedMethodAccessor154 invoke
    INFO: project gitlab-hook-plugin-mr-feature_clear_notifiers_on_mr merge target matches master
    Mar 14, 2015 12:22:45 AM org.eclipse.jetty.util.log.JavaUtilLog info
    INFO: NameError - no constructorfor arguments (java.lang.IllegalArgumentException) on Java::OrgJrubyExceptions::RaiseException:
            /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:63:in `process_projects'
            /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:30:in `POST /build_now'

**Comment by javiplx** [comment]
This should be included on acceptance tests
